name: backend_services_repository
description: This repository will be used to store and retrieve data and authenticating user
publish_to: 'none'
version: 0.01.0
environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  path: ^1.9.0
  http: ^1.2.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:  
  uses-material-design: true